export const mapPreviewTemplate = {
  id: null,
  street: null,
  house_number: null,
  formatted: null,
  offer_name: null,
  day_price: null,
  week_price: null,
  month_price: null,
  transmission: null,
  amount_seats: null,
  latitude: null,
  longitude: null,
  picture_urls: null,
};
